### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by toensing**
task 2 is still not merged into branch master

### CODE REVIEW

**Comment by manuelhaendel** [comment]
I wil make the pull request tomorrow. Still have to tweek some stuff and no time because of report.

**Comment by manuelhaendel** [comment]
OK, the task is done now. @leonthoma and @gremax93 can you please review?
One hobo_id is twice in the table. That's because it is twice in the HOBO meta data table in the same year. I could have resolved that, but I didn't want to comlicate the code even more and honestly, that's just the data that we have been given.

**Review by gremax93 — APPROVED** [review]
View is working fine. Great job

**Review by leonthoma — APPROVED** [review]
All fine !

**Pull request merged**
