### PR TITLE
Adding the resulting table

### PR DESCRIPTION
**Pull request by zoeschindler**
This is the table which results from the code. It's all of our quality checked data in one table.

### CODE REVIEW

**Review by Richterskala101 — COMMENTED** [review]
Looks great and runs smooth as well on my computer! Thanks for the good job!

**Comment by ValeGacitua** [comment]
good job!! (ﾉ◕ヮ◕)ﾉ*:・ﾟ✧🥇 
I was thinking about how to add the hobo_id in a "elegant" way (maybe creating an array to store the ID).  Anyways, that is a small detail. ;-)

**Comment by PatKac** [comment]
works without any problems for me!

**Comment by RupDe** [comment]
Works for me, too!

**Comment by PBode** [comment]
Works for me!

**Pull request closed without merging**
